Refactor rabit tests
dmlc/xgboost pull request #6096
Opened 2020-09-08 05:08 UTC by trivialfis

* Merge RABIT google tests into XGBoost.
* Run standalone tests in CTest.
* Run tests on Jenkins.

2020-09-08 05:10 UTC, trivialfis commented
Somehow there are duplicated tests defined in cc files and cpp files.

2020-09-08 05:11 UTC, trivialfis commented
@hcho3 I will do a drive by fix for #6092 .

2020-09-08 07:30 UTC, hcho3 requested changes
I did a first round of review.

You also need to change line 287 of the root CMakeLists.txt: We should install `rabit` along with `objxgboost` when `BUILD_STATIC_LIB` is on. So add it to the variable `INSTALL_TARGETS`. The reason is that Rabit is a dependency of `xgboost`, and when you install a static lib, you need to install all of its dependencies.

2020-09-08 07:30 UTC, hcho3 commented on rabit/CMakeLists.txt
>      set_target_properties(${test}  PROPERTIES CXX_STANDARD 11 CXX_STANDARD_REQUIRED ON)
```suggestion
    set_target_properties(${test}  PROPERTIES CXX_STANDARD 14 CXX_STANDARD_REQUIRED ON)
```

2020-09-08 07:31 UTC, hcho3 commented
I'll do another round of review tomorrow, as I am about to go to bed now.

2020-09-08 07:42 UTC, trivialfis commented
@hcho3 Thanks for the explanation.  Let me do some tests, I think it's possible to link multiple static libraries into one.

2020-09-08 07:44 UTC, hcho3 commented
> I think it's possible to link multiple static libraries into one.

You can turn rabit into an object library, so that librabit.a won't need to be installed. Even here, we still need to declare rabit in the export set of INSTALL(TARGETS) command.

2020-09-08 07:55 UTC, trivialfis commented
Got it, so I need to restore the installation logic.

2020-09-08 08:00 UTC, hcho3 commented
No, you can just use the installation logic in the **root** CMakeLists.txt. No need to maintain installation logic in two places.

2020-09-08 08:10 UTC, trivialfis commented
@hcho3 Thanks again.  Modified the script to install it along with objxgboost when building static library.

2020-09-09 04:09 UTC, hcho3 approved these changes

2020-09-09 04:30 UTC, merged