Add ddqdm demo.
dmlc/xgboost pull request #6156
Opened 2020-09-23 16:57 UTC by trivialfis

2020-09-23 17:01 UTC, hcho3 approved these changes

2020-09-23 17:04 UTC, hcho3 requested changes
In the commit message, please spell out `DaskDeviceQuantileDMatrix`. I was left wondering what DDQDM meant.

2020-09-23 17:05 UTC, hcho3 requested changes

2020-09-23 17:05 UTC, hcho3 commented on demo/dask/gpu_training.py
> +                print('Using QQDQM')
```suggestion
                print('Using DaskDeviceQuantileDMatrix')
```

2020-09-23 17:08 UTC, trivialfis commented
Done.

2020-09-23 17:13 UTC, hcho3 approved these changes

2020-09-24 06:08 UTC, merged

2020-09-24 06:09 UTC, hcho3 commented
Thanks a lot! I will point to this demo when I evangelize about XGBoost.Dask.