Add CUDA sm_86
dmlc/xgboost pull request #7182
Opened 2021-08-23 21:02 UTC by trivialfis

2021-08-24 05:30 UTC, trivialfis commented
@RAMitchell Could you please take a quick look into this?

2021-08-24 09:59 UTC, RAMitchell requested changes
Maybe remove 35? If I remember correctly that would be the old tesla k40 cards.

2021-08-24 10:34 UTC, trivialfis commented
@RAMitchell Done.

Time flies. ;-)

2021-08-25 00:27 UTC, RAMitchell approved these changes

2021-08-25 08:04 UTC, merged