[breaking] Change internal model serialization to UBJSON.
dmlc/xgboost pull request #7556
Opened 2022-01-11 06:47 UTC by trivialfis

* Use typed array for models.
* Change the memory snapshot format.
* Add new C API for saving to raw format.

This PR breaks the schema of JSON, the `default_left` field is changed from boolean to integer so that we can use typed array.  XGBoost itself will continue to load the old models, third-party libraries that depend on this schema will have to make changes accordingly.  I can help with treelite once the full PR is merged.

Extracted from https://github.com/dmlc/xgboost/pull/7545 .

2022-01-13 16:01 UTC, hcho3 commented
> I can help with treelite once the full PR is merged.

Treelite doesn't need to be updated, since it already handles integer arrays for `default_left`. See dmlc/treelite#337.

2022-01-13 16:19 UTC, trivialfis commented
Ah, the parser is interesting, I should learn more about it.  Thanks for sharing.

2022-01-14 04:44 UTC, hcho3 requested changes

2022-01-14 04:45 UTC, trivialfis commented on include/xgboost/c_api.h
> + *                    following available fields in the JSON object:
Let me change that.

2022-01-14 05:22 UTC, trivialfis commented on include/xgboost/c_api.h
> + *                    following available fields in the JSON object:
Reverted.

2022-01-14 06:23 UTC, trivialfis commented
@hcho3 Could you please take another look?

2022-01-14 08:03 UTC, trivialfis commented
Added an extra optimization to avoid the i64 array for split index.  Also, fixed the type used in the tree param.

2022-01-15 18:04 UTC, RAMitchell approved these changes

2022-01-15 18:11 UTC, merged