[WIP] v1.6 release note. [skip ci]
dmlc/xgboost pull request #7746
Opened 2022-03-22 21:02 UTC by trivialfis

2022-03-22 23:20 UTC, hcho3 commented on NEWS.md
> +* Binary package Support Apple Silicon. (#7621, #7612)
```suggestion
* Pre-built binary wheel for Apple Silicon. (#7621, #7612) Apple Silicon users will now be able to run `pip install xgboost` to install XGBoost.
```

Can you also merge in https://github.com/dmlc/xgboost/pull/7747 as part of 1.6 release?

2022-03-23 03:21 UTC, wbo4958 commented
Could we wait for https://github.com/dmlc/xgboost/pull/7709 ?

2022-03-28 11:24 UTC, trivialfis commented
https://github.com/dmlc/xgboost/pull/7759
https://github.com/dmlc/xgboost/pull/7752
https://github.com/dmlc/xgboost/pull/7756
https://github.com/dmlc/xgboost/pull/7759

2022-03-28 20:05 UTC, trivialfis commented on NEWS.md
> +* Deterministic result for evaluation metric and linear model In previous versions of
```suggestion
* Deterministic result for evaluation metric and linear model. In previous versions of
```

2022-03-31 17:57 UTC, trivialfis commented on NEWS.md
> +- Supports for categorical data.
```suggestion
- Support for categorical data.
```

2022-04-02 00:09 UTC, wbo4958 commented
Please hold on, I would like to add some doc and samples for the GPU supporting in JVM package these days. @trivialfis

2022-04-05 01:18 UTC, wbo4958 commented
Hi @trivialfis, could you add this PR in 1.6.0 release https://github.com/dmlc/xgboost/pull/7784 thx

2022-04-07 11:11 UTC, wbo4958 commented
@trivialfis, could you add this PR in 1.6.0 release https://github.com/dmlc/xgboost/pull/7789

2022-04-16 04:22 UTC, hcho3 commented
Is this still WIP?

2022-04-16 04:39 UTC, trivialfis commented
@hcho3 Changed the title.  It's complete.

2022-04-16 08:18 UTC, hcho3 requested changes

2022-04-16 08:18 UTC, hcho3 commented on NEWS.md
> +and `gpu_hist` now supports training with categorical data.  Also, partition-based
```suggestion
and `gpu_hist` now support training with categorical data.  Also, partition-based
```

2022-04-16 08:18 UTC, hcho3 commented on NEWS.md
> +categorical split is featured in this release. This split type is first available in
```suggestion
categorical split is introduced in this release. This split type is first available in
```

2022-04-16 08:18 UTC, hcho3 commented on NEWS.md
> +for the left and right nodes using any of the aforementioned tree methods. For more
```suggestion
LightGBM in the context of gradient boosting. The previous XGBoost release supported one-hot split where the splitting criteria is of form `x \in {c}`, i.e. the categorical feature `x` is tested against a single candidate. The new release allows for more expressive conditions: `x \in S` where the categorical feature `x` is tested against multiple candidates. Moreover, it is now possible to use any tree algorithms (`hist`, `approx`, `gpu_hist`) when creating categorical splits. For more
```

2022-04-16 08:18 UTC, hcho3 commented on NEWS.md
> +The `approx` tree method is rewritten based on the existing `hist` tree method, the
```suggestion
The `approx` tree method is rewritten based on the existing `hist` tree method. The
```

2022-04-16 08:18 UTC, hcho3 commented on NEWS.md
> +Now the behavior and `approx` should be more aligned with `hist` and `gpu_hist`, here's a
```suggestion
Now the behavior of `approx` should be more aligned with `hist` and `gpu_hist`. Here is a
```

2022-04-16 08:26 UTC, hcho3 approved these changes

2022-04-16 08:27 UTC, merged