Add convergence test for sparse datasets.
dmlc/xgboost pull request #7922
Opened 2022-05-20 03:59 UTC by trivialfis

2022-05-20 04:09 UTC, trivialfis commented
We will add tests for categorical data later.

2022-05-23 08:19 UTC, hcho3 requested changes

2022-05-23 08:36 UTC, trivialfis commented on tests/python-gpu/test_gpu_updaters.py
> +        approx_result = train_result(param, dataset.get_dmat(), 16)
Good catch!

2022-05-23 08:44 UTC, hcho3 approved these changes

2022-05-23 10:07 UTC, merged