[CI] Prune unused archs from libnccl
dmlc/xgboost pull request #8179
Opened 2022-08-17 10:07 UTC by hcho3

This further reduces the size of the compiled binary.

2022-08-17 11:16 UTC, trivialfis requested changes
Thank you for working on this. I think this needs to be a CI specific change. People might not want XGBoost to prune the nccl on their system.

2022-08-17 12:44 UTC, RAMitchell reviewed
Agree with Jiaming that users self installing probably don't need this, and it could easily break their install process.

Is it possible to create the option PRUNE_NCCL which performs the prune then modifies the nccl library path variable in find_nccl.

2022-08-17 12:44 UTC, RAMitchell commented on CMakeLists.txt
> +    add_custom_target(PruneLibNccl nvprune ${GEN_CODE} /usr/lib64/libnccl_static.a -o libnccl_static.a)
Should this path be hardcoded?

2022-08-17 16:23 UTC, hcho3 commented
> People might not want XGBoost to prune the nccl on their system.

The custom target is entirely optional, as it's not part of the `all` target. So you need to explicitly opt in: `ninja PruneLibNccl`

2022-08-17 16:28 UTC, hcho3 commented
> Is it possible to create the option PRUNE_NCCL which performs the prune then modifies the nccl library path variable in find_nccl.

This is hard, as you'd need to modify the nccl path as a result of building a target.

2022-08-17 22:47 UTC, hcho3 commented
@trivialfis @RAMitchell I revised this pull request so that the changes are restricted to scripts in the CI directory `tests/ci_build`. Can you review again?

2022-08-18 12:58 UTC, RAMitchell commented
Thanks. I was curious if it can be done in pure cmake with a bit less hacking, here is my attempt: #8183. Not sure if it's any better.

2022-08-19 12:35 UTC, RAMitchell commented
Let's go with this version I think.

2022-08-19 12:35 UTC, RAMitchell approved these changes

2022-08-21 08:03 UTC, trivialfis approved these changes

2022-08-21 08:46 UTC, merged