[CI] Revise R tests.
dmlc/xgboost pull request #8430
Opened 2022-11-06 21:13 UTC by trivialfis

- Use the standard package check (check on the tarball instead of the source tree).
- Run commands in parallel.
- Cleanup dependencies installation.
- Replace makefile.
- Documentation.
- Optional test with rhub.

Close https://github.com/dmlc/xgboost/issues/8429 .

2022-11-06 21:16 UTC, trivialfis commented on .github/workflows/r_rhub.yml
> +    # We use rhub to launch container here
remove

2022-11-06 21:16 UTC, trivialfis commented on R-package/tests/helper_scripts/install_deps.R
> +  print("Installing source package on unix.")
typo.

2022-11-06 21:16 UTC, trivialfis commented on R-package/tests/helper_scripts/install_deps.R
> +  print("Installing binary package on Windows.")
typo.

2022-11-06 22:54 UTC, trivialfis commented
/gha run rhub-test

2022-11-06 23:01 UTC, trivialfis commented
/gha run rhub-test

2022-11-06 23:09 UTC, trivialfis commented on .github/workflows/r_rhub.yml
> +  pull_request_review_comment:
/gha run r-hub-test

2022-11-06 23:14 UTC, trivialfis commented on .github/workflows/r_rhub.yml
> +  pull_request_review_comment:
/gha run r-hub-test

2022-11-06 23:15 UTC, trivialfis commented on .github/workflows/r_rhub.yml
> +  pull_request_review_comment:
/gha run rhub-test

2022-11-06 23:17 UTC, trivialfis commented on .github/workflows/r_rhub.yml
> +  pull_request_review_comment:
/gha run rhub-test

2022-11-06 23:44 UTC, trivialfis commented on .github/workflows/r_rhub.yml
> +  pull_request_review_comment:
/gha run rhub-test

2022-11-07 00:11 UTC, trivialfis commented on .github/workflows/r_rhub.yml
> +  pull_request_review_comment:
/gha run r-nold-test

2022-11-07 00:12 UTC, trivialfis commented on .github/workflows/r_rhub.yml
> +  pull_request_review_comment:
/gha run r-nold-test

2022-11-07 01:13 UTC, trivialfis commented on .github/workflows/r_rhub.yml
> +  pull_request_review_comment:
/gha run r-nold-test

2022-11-08 05:06 UTC, hcho3 requested changes

2022-11-08 21:41 UTC, hcho3 approved these changes

2022-11-09 01:12 UTC, merged