Enable Installation of Python Package with System lib in a Virtual Environment
dmlc/xgboost pull request #9349
Opened 2023-06-30 10:22 UTC by oliverholworthy

## Goal

Enable Installation of Python Package with System lib in a Virtual Environment

## Motivation

Setting up tests to run inside a virtual environment in an image that has xgboost pre-installed as a system lib. (e.g. `nvcr.io/nvidia/tensorflow:23.06-tf2-py3`). When in a virtual environment, the `sys.prefix` changes to point to the `lib` directory inside the virtualenvironment instead of the system lib path. 
- Installing xgboost with the `use_system_libxgboost=True` in a virtual environment
- Using a `tox` virtual environment with `sitepackages=true` to pickup an xgboost installation present on the system already

2023-06-30 21:52 UTC, trivialfis reviewed
Thank you for the work on improved support with venv. However, I got a bit confused by the paths now. Maybe we need a new option that's more general as discussed in https://github.com/dmlc/xgboost/issues/6706, specifically https://github.com/dmlc/xgboost/issues/6706#issuecomment-813783117. Without a new option, it's difficult to handle the diversity of packaging methods. In the case of venv, the shared can be in `/usr/lib` or `myvenv/lib`, or `myvenv/lib/python3.x/site-packages/xgboost/lib`.

2023-06-30 22:14 UTC, hcho3 requested changes
There are times when we need to use sys.prefix. Example: libxgboost is installed inside a Conda enviornment.

2023-06-30 22:20 UTC, trivialfis commented
I think mamba always copies the python executable, so the base_prefix and the prefix are the same:
```
Python 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.base_prefix
'/home/jiamingy/.anaconda/envs/xgboost_dev'
>>> sys.prefix
'/home/jiamingy/.anaconda/envs/xgboost_dev'
```
I expect conda to have the same behavior.

2023-06-30 22:37 UTC, hcho3 commented
It would be nice to make paths user configurable

2023-06-30 22:59 UTC, hcho3 approved these changes
I realize that this PR doesn't break Conda. For now this change is fine. In a future PR, we can add user configuration for paths.

2023-07-03 19:32 UTC, trivialfis approved these changes

2023-07-03 21:16 UTC, trivialfis commented
I canceled the job for the stalling test. It's caused by an issue in column-split test, which has been fixed in master branch. Will rebase the PR.

2023-07-04 21:46 UTC, merged

2023-07-11 00:32 UTC, trivialfis commented
@hcho3 @oliverholworthy After reading the mamba document: https://mamba.readthedocs.io/en/latest/advanced_usage/more_concepts.html#linking I think this PR might be problematic if there are users who prefer soft-links.

2023-07-11 00:36 UTC, hcho3 commented
Thanks, I opened #9376 as a reminder.