Define `best_iteration` only if early stopping is used.
dmlc/xgboost pull request #9403
Opened 2023-07-20 04:22 UTC by trivialfis

This is the behavior specified by the document but not honored in the actual code. The improvement calculated in early stopping is a bit more complicated than regular monitoring as it has options like `min_delta`. Leaving it to early stopping to prevent incosisent behaviours.

- Don't set the attributes if there's no early stopping.
- Cleanup the code for callbacks and replace assertions with proper exceptions.
- Assign the attributes when early stopping `save_best` is used.
- Turn the attributes into Python properties.

2023-07-21 23:55 UTC, hcho3 requested changes

2023-07-21 23:55 UTC, hcho3 commented on python-package/xgboost/sklearn.py
> +        Sampling method. Used only by the GPU version of `hist` tree method.
```suggestion
        Sampling method. Used only by the GPU version of ``hist`` tree method.
```

2023-07-21 23:55 UTC, hcho3 commented on python-package/xgboost/sklearn.py
>            - `uniform`: select random training instances uniformly.
```suggestion
          - ``uniform``: select random training instances uniformly.
```

2023-07-21 23:55 UTC, hcho3 commented on python-package/xgboost/sklearn.py
> +            when the gradient and hessian are larger. (cf. CatBoost)
```suggestion
          - ``gradient_based`` select random training instances with higher probability
            when the gradient and hessian are larger. (cf. CatBoost)
```

2023-07-21 23:55 UTC, hcho3 commented on tests/python/test_callback.py
> +            booster='gblinear',
```suggestion
            booster="gblinear",
```

2023-07-22 09:01 UTC, trivialfis commented
@hcho3 All changes applied.

2023-07-23 18:15 UTC, hcho3 approved these changes

2023-07-24 04:43 UTC, merged