[doc] Mention data consistency for categorical features.
dmlc/xgboost pull request #9678
Opened 2023-10-16 06:45 UTC by trivialfis

2023-10-19 01:51 UTC, hcho3 requested changes

2023-10-19 01:51 UTC, hcho3 commented on demo/guide-python/cat_in_the_dat.py
> +  .. versionadded 1.6.0
```suggestion
  .. versionadded:: 1.6.0
```

2023-10-19 01:51 UTC, hcho3 commented on doc/tutorials/categorical.rst
> +XGBoost accepts parameters for which feature is considered categorical, either through the ``dtypes`` of a dataframe or through the ``feature_types`` parameter. However, XGBoost by itself doesn't sto
```suggestion
XGBoost accepts parameters to indicate which feature is considered categorical, either through the ``dtypes`` of a dataframe or through the ``feature_types`` parameter. However, XGBoost by itself doesn't store information on how categories are encoded in the first place. For instance, given an encoding schema that maps music genres to integer codes:
```

2023-10-19 09:34 UTC, trivialfis commented
Added an example script based on https://github.com/dmlc/xgboost/issues/9676#issuecomment-1768045040 , along with tests.

2023-10-23 10:07 UTC, trivialfis commented
@hcho3 Could you please take another look?

2023-10-23 21:58 UTC, hcho3 approved these changes

2023-10-24 02:11 UTC, merged